
#docker-compose file controls how to run the container that will be built
#based upon our Dockerfile image.

version: '3.8'

services:
    web:
        # look for Dockerfile in the directory
        build: .
        command: gunicorn config.wsgi -b 0.0.0.0:8000
        # syncs changes between Docker and local
        volumes:
            - .:/code
        ports:
            - 8000:8000
        
        # db will start up before our web service because of depends_on
        depends_on:
            - db
        environment:
            - "DJANGO_SECRET_KEY=django-insecure-k!xaco+=1j5tk7t&x=xfe!5dxs$wscqb=8db5mgsmt@1h(66z="
            - "DJANGO_DEBUG=True"
            - "DJANGO_SECURE_SSL_REDIRECT=False"
            - "DJANGO_SECURE_HSTS_SECONDS=0"
            - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
            - "DJANGO_SECURE_HSTS_PRELOAD=False"
            - "DJANGO_SESSION_COOKIE_SECURE=False"
            - "DJANGO_CSRF_COOKIE_SECURE=False"
            - "AWS_ACCESS_KEY_ID=AKIAR2UYSJ3QKACKFXIO"
            - "AWS_SECRET_ACCESS_KEY=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"
            - "S3_BUCKET=creativeblogbucket"
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - 'POSTGRES_HOST_AUTH_METHOD=trust'
volumes:
    postgres_data:
